// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDy-3fiyU4eksqDOK9qo1wvECdIKLNTLj0',
    appId: '1:10843096048:web:fcf1ef1d07182c8c06d335',
    messagingSenderId: '10843096048',
    projectId: 'ffproject-fd396',
    authDomain: 'ffproject-fd396.firebaseapp.com',
    storageBucket: 'ffproject-fd396.appspot.com',
    measurementId: 'G-YVGSZWY8FY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIX7Sm-8xmmLNfxHLJzumKNYEm7ynkWTQ',
    appId: '1:10843096048:android:a05db3c5ca10616b06d335',
    messagingSenderId: '10843096048',
    projectId: 'ffproject-fd396',
    storageBucket: 'ffproject-fd396.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-YEBOlyCpmXWShB6F6njBlWNIrtXAAG0',
    appId: '1:10843096048:ios:50bb98995805b17806d335',
    messagingSenderId: '10843096048',
    projectId: 'ffproject-fd396',
    storageBucket: 'ffproject-fd396.appspot.com',
    iosBundleId: 'com.example.antesProva',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-YEBOlyCpmXWShB6F6njBlWNIrtXAAG0',
    appId: '1:10843096048:ios:50bb98995805b17806d335',
    messagingSenderId: '10843096048',
    projectId: 'ffproject-fd396',
    storageBucket: 'ffproject-fd396.appspot.com',
    iosBundleId: 'com.example.antesProva',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDy-3fiyU4eksqDOK9qo1wvECdIKLNTLj0',
    appId: '1:10843096048:web:0062682e881c3a9a06d335',
    messagingSenderId: '10843096048',
    projectId: 'ffproject-fd396',
    authDomain: 'ffproject-fd396.firebaseapp.com',
    storageBucket: 'ffproject-fd396.appspot.com',
    measurementId: 'G-78Z11VWR73',
  );
}
